[package]
name = "pingsender-rs"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
reqwest = "0.8.5"
flate2 = "1.0.1"
log = "0.4.1"
env_logger = "0.5.6"

[profile.release]
lto = true
panic = 'abort'
